image: "rust:alpine"

include:
  - template: Jobs/SAST.gitlab-ci.yml

default:
  before_script:
    - mkdir -p $APK_CACHE_DIR
    - echo "@edgecommunity https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - apk add --cache-dir $APK_CACHE_DIR --update perl make pkgconfig musl-dev libc-dev gcc zig@edgecommunity
    - rustup component add clippy
  cache:
    paths:
      - target
      - .rigz # used when rigz cli is run (TODO)
      - rigz_runtime/.rigz # initialize will clone or check the folder path, speed up testing
      - $APK_CACHE_DIR

variables:
  APK_CACHE_DIR: $CI_PROJECT_DIR/.cache/apk
  C_INCLUDE_PATH: "/usr/include"

stages:
  - test
  # - publish

test:cargo:
  stage: test
  needs: []
  script:
    - rustc --version && cargo --version
    - cargo test --all

test:clippy:
  stage: test
  needs: []
  script:
    - rustc --version && cargo --version
    - cargo clippy

# store .h files as artifacts
#
#test:module_runtime:
#  stage: test
#  script:
#    - cd rigz_modules/
#    - zig test
#  needs:
#    - job: test:cargo
#      artifacts: true
#
#test:std_lib:
#  stage: test
#  script:
#    - cd rigz_modules/
#    - zig test
#  needs:
#    - job: test:cargo
#      artifacts: true
#
#publish:
#  stage: publish