image: "rust:alpine"

default:
  before_script:
    - echo "@edgecommunity https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - apk add --update musl-dev zig@edgecommunity
  cache:
    paths:
      - target

test:cargo:
  script:
    - rustc --version && cargo --version
    - cargo test --all