image: "rust:alpine"

default:
  before_script:
    - mkdir -p $APK_CACHE_DIR
    - echo "@edgecommunity https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - apk add --cache-dir $APK_CACHE_DIR --update libffi-dev openssl-dev pkgconfig musl-dev libc-dev gcc zig@edgecommunity
  cache:
    paths:
      - target
      - $APK_CACHE_DIR

variables:
  APK_CACHE_DIR: $CI_PROJECT_DIR/.cache/apk
  C_INCLUDE_PATH: "/usr/include"
  OPENSSL_INCLUDE_DIR: "/usr/include"
  OPENSSL_LIB_DIR: "/usr/lib"
  OPENSSL_STATIC: 1 # https://github.com/sfackler/rust-openssl/issues/1627#issuecomment-1958587430

stages:
  - test
  # - publish

test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --all

# store .h files as artifacts
#
#test:module_runtime:
#  stage: test
#  script:
#    - cd rigz_modules/
#    - zig test
#  needs:
#    - job: test:cargo
#      artifacts: true
#
#test:std_lib:
#  stage: test
#  script:
#    - cd rigz_modules/
#    - zig test
#  needs:
#    - job: test:cargo
#      artifacts: true
#
#publish:
#  stage: publish