# Use Alpine Linux as the base image
FROM rust:alpine

RUN echo "@edgecommunity https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

# Install necessary packages
RUN apk update && \
    apk add --no-cache musl-dev libc-dev gcc zig@edgecommunity

# Set environment variables
ENV C_INCLUDE_PATH="/usr/include"

# Set up workspace
WORKDIR /workspace

# Copy your project files into the container
COPY . .

# Run shell by default
CMD ["sh"]
