[package]
name = "rigz_runtime"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
glob = "0.3.1"
log = { version = "0.4.21", features = [] }
rigz_parse = { path = "../rigz_parse" }
serde = { version = "1.0.200", features = ["derive"] }