[package]
name = "rigz_runtime"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
rigz_core = { path = "../rigz_core" } # required to generated header file

[dependencies]
anyhow = "1.0.82"
openssl = { version = "0.10", features = ["vendored"] }
git2 = "0.18.3"
glob = "0.3.1"
log = { version = "0.4.21", features = [] }
rigz_core = { path = "../rigz_core" }
rigz_parse = { path = "../rigz_parse" }
serde = { version = "1.0.200", features = ["derive"] }
serde-value = "0.7.0"
