[lib]
crate-type = ["lib", "staticlib"]

[package]
name = "rigz_core"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
log = { workspace = true, features = [] }
serde = { version = "1.0.200", features = ["derive"] }
